{% set name = "beamfit" %}
{% set version = "1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beamfit-{{ version }}.tar.gz
  sha256: 2d64ed284849eedbf0bbf42eeebaefb5f57377034b250fe53f84d1eb77edc6aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy
    - matplotlib-base
    - pydantic
    - scipy

test:
  imports:
    - beamfit
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Robust laser and charged particle beam image analysis
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/electronsandstuff/beamfit

extra:
  recipe-maintainers:
    - electronsandstuff
    - ken-lauer
