{% set name = "beamfit" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beamfit-{{ version }}.tar.gz
  sha256: 6e6a023e52507ba44dd93eb21267c9484ee995d2a397f91eb6a929b5bbbd313c

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=64
    - wheel
    - numpy
    - pip
  run:
    - python
    - matplotlib-base
    - scipy
    - numpy

test:
  imports:
    - beamfit
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Robust laser and charged particle beam image analysis
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/electronsandstuff/beamfit

extra:
  recipe-maintainers:
    - ken-lauer
